/*
** EPITECH PROJECT, 2023
** raytracer
** File description:
** SFMLKeyEventMap
*/

#include <SFML/Window/Keyboard.hpp>
#include "EventManager.hpp"
#include <map>

const std::map<sf::Keyboard::Key, RayTracer::Core::EventType> SFMLKeyEventMap = {
    {sf::Keyboard::A, RayTracer::Core::EventType::KEY_A_PRESSED},
    {sf::Keyboard::B, RayTracer::Core::EventType::KEY_B_PRESSED},
    {sf::Keyboard::C, RayTracer::Core::EventType::KEY_C_PRESSED},
    {sf::Keyboard::D, RayTracer::Core::EventType::KEY_D_PRESSED},
    {sf::Keyboard::E, RayTracer::Core::EventType::KEY_E_PRESSED},
    {sf::Keyboard::F, RayTracer::Core::EventType::KEY_F_PRESSED},
    {sf::Keyboard::G, RayTracer::Core::EventType::KEY_G_PRESSED},
    {sf::Keyboard::H, RayTracer::Core::EventType::KEY_H_PRESSED},
    {sf::Keyboard::I, RayTracer::Core::EventType::KEY_I_PRESSED},
    {sf::Keyboard::J, RayTracer::Core::EventType::KEY_J_PRESSED},
    {sf::Keyboard::K, RayTracer::Core::EventType::KEY_K_PRESSED},
    {sf::Keyboard::L, RayTracer::Core::EventType::KEY_L_PRESSED},
    {sf::Keyboard::M, RayTracer::Core::EventType::KEY_M_PRESSED},
    {sf::Keyboard::N, RayTracer::Core::EventType::KEY_N_PRESSED},
    {sf::Keyboard::O, RayTracer::Core::EventType::KEY_O_PRESSED},
    {sf::Keyboard::P, RayTracer::Core::EventType::KEY_P_PRESSED},
    {sf::Keyboard::Q, RayTracer::Core::EventType::KEY_Q_PRESSED},
    {sf::Keyboard::R, RayTracer::Core::EventType::KEY_R_PRESSED},
    {sf::Keyboard::S, RayTracer::Core::EventType::KEY_S_PRESSED},
    {sf::Keyboard::T, RayTracer::Core::EventType::KEY_T_PRESSED},
    {sf::Keyboard::U, RayTracer::Core::EventType::KEY_U_PRESSED},
    {sf::Keyboard::V, RayTracer::Core::EventType::KEY_V_PRESSED},
    {sf::Keyboard::W, RayTracer::Core::EventType::KEY_W_PRESSED},
    {sf::Keyboard::X, RayTracer::Core::EventType::KEY_X_PRESSED},
    {sf::Keyboard::Y, RayTracer::Core::EventType::KEY_Y_PRESSED},
    {sf::Keyboard::Z, RayTracer::Core::EventType::KEY_Z_PRESSED},
    {sf::Keyboard::Num0, RayTracer::Core::EventType::KEY_0_PRESSED},
    {sf::Keyboard::Num1, RayTracer::Core::EventType::KEY_1_PRESSED},
    {sf::Keyboard::Num2, RayTracer::Core::EventType::KEY_2_PRESSED},
    {sf::Keyboard::Num3, RayTracer::Core::EventType::KEY_3_PRESSED},
    {sf::Keyboard::Num4, RayTracer::Core::EventType::KEY_4_PRESSED},
    {sf::Keyboard::Num5, RayTracer::Core::EventType::KEY_5_PRESSED},
    {sf::Keyboard::Num6, RayTracer::Core::EventType::KEY_6_PRESSED},
    {sf::Keyboard::Num7, RayTracer::Core::EventType::KEY_7_PRESSED},
    {sf::Keyboard::Num8, RayTracer::Core::EventType::KEY_8_PRESSED},
    {sf::Keyboard::Num9, RayTracer::Core::EventType::KEY_9_PRESSED},
    {sf::Keyboard::Up, RayTracer::Core::EventType::KEY_UP_PRESSED},
    {sf::Keyboard::Down, RayTracer::Core::EventType::KEY_DOWN_PRESSED},
    {sf::Keyboard::Left, RayTracer::Core::EventType::KEY_LEFT_PRESSED},
    {sf::Keyboard::Right, RayTracer::Core::EventType::KEY_RIGHT_PRESSED},
    {sf::Keyboard::Space, RayTracer::Core::EventType::KEY_SPACE_PRESSED},
    {sf::Keyboard::Return, RayTracer::Core::EventType::KEY_ENTER_PRESSED},
    {sf::Keyboard::Delete, RayTracer::Core::EventType::KEY_BACKSPACE_PRESSED},
    {sf::Keyboard::Tab, RayTracer::Core::EventType::KEY_TAB_PRESSED},
    {sf::Keyboard::LShift, RayTracer::Core::EventType::KEY_SHIFT_PRESSED},
    {sf::Keyboard::RShift, RayTracer::Core::EventType::KEY_SHIFT_PRESSED},
    {sf::Keyboard::LControl, RayTracer::Core::EventType::KEY_CTRL_PRESSED},
    {sf::Keyboard::RControl, RayTracer::Core::EventType::KEY_CTRL_PRESSED},
    {sf::Keyboard::LAlt, RayTracer::Core::EventType::KEY_ALT_PRESSED},
    {sf::Keyboard::RAlt, RayTracer::Core::EventType::KEY_ALT_PRESSED},
    {sf::Keyboard::F1, RayTracer::Core::EventType::KEY_F1_PRESSED},
    {sf::Keyboard::F2, RayTracer::Core::EventType::KEY_F2_PRESSED},
    {sf::Keyboard::F3, RayTracer::Core::EventType::KEY_F3_PRESSED},
    {sf::Keyboard::F4, RayTracer::Core::EventType::KEY_F4_PRESSED},
    {sf::Keyboard::F5, RayTracer::Core::EventType::KEY_F5_PRESSED},
    {sf::Keyboard::F6, RayTracer::Core::EventType::KEY_F6_PRESSED},
    {sf::Keyboard::F7, RayTracer::Core::EventType::KEY_F7_PRESSED},
    {sf::Keyboard::F8, RayTracer::Core::EventType::KEY_F8_PRESSED},
    {sf::Keyboard::F9, RayTracer::Core::EventType::KEY_F9_PRESSED},
    {sf::Keyboard::F10, RayTracer::Core::EventType::KEY_F10_PRESSED},
    {sf::Keyboard::F11, RayTracer::Core::EventType::KEY_F11_PRESSED},
    {sf::Keyboard::F12, RayTracer::Core::EventType::KEY_F12_PRESSED},
    {sf::Keyboard::Escape, RayTracer::Core::EventType::KEY_ESCAPE_PRESSED},
};
