name: CI-CD

on: [push, pull_request]

env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-OOP-400-TLS-4-1-raytracer-clement.lagasse.git
  CACHE_KEY: raytracer-cache

jobs:
  check_repository_cleanliness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: check good files & folders
        run : |
          paths=($(find . -name '#*#' -o -name '*-' -o -name '*.tmp' -o -name '*.o' -o -name '*.a' -o -name '*.so' -o -name '*.gcno' -o -name '*.gcda' -o -name '*.gcov' -o -type d -name 'tmp'))
          if [[ ! -z "$path" ]]; then
            IFS=$'\n'
            for FILE in "${paths[@]}"; do echo "::error title=Unwanted file detected,file=$FILE::$FILE"; done
            unset IFS
            exit 1
          fi

  check_program_compilation:
    needs : check_repository_cleanliness
    runs-on: ubuntu-latest
    container: theophilushmwo/custom-epitest-docker
    steps:
      - uses: actions/checkout@v3

      - name: Cache compiled raytracer and plugins
        id: cache-raytracer
        uses: actions/cache@v3
        with:
          path: |
            ./raytracer
            ./plugins
          key: ${{ env.CACHE_KEY }}-${{ github.run_id }}
          restore-keys: ${{ env.CACHE_KEY }}-

      - name: cmake
        if: steps.cache-raytracer.outputs.cache-hit != 'true'
        run: timeout 2m cmake .
      - name: make for makefile
        if: steps.cache-raytracer.outputs.cache-hit != 'true'
        run: timeout 2m make -j 16

    test_image_ppm:
      needs: check_program_compilation
      runs-on: ubuntu-latest
      container: clemlgss/my-raytracer
      steps:
        - uses: actions/checkout@v3

        - name: Cache compiled raytracer and plugins
          id: cache-raytracer
          uses: actions/cache@v3
          with:
            path: |
              ./raytracer
              ./plugins
            key: ${{ env.CACHE_KEY }}-${{ github.run_id }}
            restore-keys: ${{ env.CACHE_KEY }}-

        - name: test image ppm
          run: ./raytracer POCGraph --test
        - name: test diff
          run: diff poc.ppm tests/poc.ppm.expected

  push_to_mirror:
    needs: test_image_ppm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
